spring:
  application:
    name: vartaos-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ritwikupadhyay
    username: ritwikupadhyay
    password: varta123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true