spring:
  application:
    name: vartaos-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ritwikupadhyay
    username: ritwikupadhyay
    password: varta123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 5vM2qJk8Lp9XsR7bN4eTf1HyW6ZaQ3mCd8PwEr2YuIoKjLxVzBn
  expiration: 86400000

gemini:
  api:
    key: ${GEMINI_API_KEY}