package com.vartaos.vartaosbackend.entity.enums;

/**
 * Represents the sender of a message inside an AI conversation.
 *
 * USER -> Message sent by the student.
 * AI   -> Message generated by the AI tutor.
 *
 * @author Ritwik
 * @since VartaOS v1
 */
public enum MessageSender {

    /**
     * Student/User message.
     */
    USER,

    /**
     * AI-generated message.
     */
    AI
}